# -*- coding: utf-8 -*-
"""Final Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LmIGvQ__88xfueY5abskFekJQkJdSadD
"""

import pandas as pd
import numpy as np

df = pd.read_csv("newspopularitydataset.csv")
df.head()

df.columns = df.columns.str.strip()

df.head()

# checking for missing values
df.isnull().sum().sort_values(ascending=False).head(10)

import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

plt.figure(figsize=(8, 5))
plt.hist(df["shares"], bins=50)
plt.xlabel("Shares")
plt.ylabel("Number of Articles")
plt.title("Distribution of Article Shares")
plt.show()

df["log_shares"] = np.log1p(df["shares"])

plt.figure(figsize=(8, 5))
plt.hist(df["log_shares"], bins=50)
plt.xlabel("Log Shares")
plt.ylabel("Number of Articles")
plt.title("Distribution of Log-Transformed Article Shares")
plt.show()

median_shares = df["shares"].median()

df["popular"] = (df["shares"] >= median_shares).astype(int)

print("Median shares:", median_shares)
df["popular"].value_counts()

df["popular"].value_counts(normalize=True)

plt.figure(figsize=(6, 4))
df["popular"].value_counts().sort_index().plot(kind="bar")
plt.xlabel("Popular Class")
plt.ylabel("Number of Articles")
plt.title("Class Balance: Not Popular vs Popular")
plt.xticks([0, 1], ["Not Popular", "Popular"], rotation=0)
plt.show()

columns_to_drop = ["url", "shares", "log_shares", "popular"]

X = df.drop(columns=columns_to_drop)
y = df["popular"]

print("X shape:", X.shape)
print("y shape:", y.shape)

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training rows:", X_train.shape[0])
print("Testing rows:", X_test.shape[0])

print("Training class balance:")
print(y_train.value_counts(normalize=True))

print("\nTesting class balance:")
print(y_test.value_counts(normalize=True))

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

from sklearn.dummy import DummyClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report

baseline = DummyClassifier(strategy="most_frequent", random_state=42)

baseline.fit(X_train, y_train)

baseline_preds = baseline.predict(X_test)

print("Baseline Accuracy:", accuracy_score(y_test, baseline_preds))
print("Baseline Precision:", precision_score(y_test, baseline_preds, zero_division=0))
print("Baseline Recall:", recall_score(y_test, baseline_preds, zero_division=0))
print("Baseline F1:", f1_score(y_test, baseline_preds, zero_division=0))

print("\nClassification Report:")
print(classification_report(y_test, baseline_preds, zero_division=0))

from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression(max_iter=1000, random_state=42)

log_reg.fit(X_train_scaled, y_train)

log_reg_preds = log_reg.predict(X_test_scaled)

print("Logistic Regression Accuracy:", accuracy_score(y_test, log_reg_preds))
print("Logistic Regression Precision:", precision_score(y_test, log_reg_preds))
print("Logistic Regression Recall:", recall_score(y_test, log_reg_preds))
print("Logistic Regression F1:", f1_score(y_test, log_reg_preds))

print("\nClassification Report:")
print(classification_report(y_test, log_reg_preds))

from sklearn.tree import DecisionTreeClassifier

tree = DecisionTreeClassifier(
    max_depth=5,
    random_state=42
)

tree.fit(X_train, y_train)

tree_preds = tree.predict(X_test)

print("Decision Tree Accuracy:", accuracy_score(y_test, tree_preds))
print("Decision Tree Precision:", precision_score(y_test, tree_preds))
print("Decision Tree Recall:", recall_score(y_test, tree_preds))
print("Decision Tree F1:", f1_score(y_test, tree_preds))

print("\nClassification Report:")
print(classification_report(y_test, tree_preds))

from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=100,
    max_depth=10,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)

rf_preds = rf.predict(X_test)

print("Random Forest Accuracy:", accuracy_score(y_test, rf_preds))
print("Random Forest Precision:", precision_score(y_test, rf_preds))
print("Random Forest Recall:", recall_score(y_test, rf_preds))
print("Random Forest F1:", f1_score(y_test, rf_preds))

print("\nClassification Report:")
print(classification_report(y_test, rf_preds))

from sklearn.ensemble import GradientBoostingClassifier

gb = GradientBoostingClassifier(
    random_state=42
)

gb.fit(X_train, y_train)

gb_preds = gb.predict(X_test)

print("Gradient Boosting Accuracy:", accuracy_score(y_test, gb_preds))
print("Gradient Boosting Precision:", precision_score(y_test, gb_preds))
print("Gradient Boosting Recall:", recall_score(y_test, gb_preds))
print("Gradient Boosting F1:", f1_score(y_test, gb_preds))

print("\nClassification Report:")
print(classification_report(y_test, gb_preds))

results = pd.DataFrame({
    "Model": [
        "Baseline",
        "Logistic Regression",
        "Decision Tree",
        "Random Forest",
        "Gradient Boosting"
    ],
    "Accuracy": [
        accuracy_score(y_test, baseline_preds),
        accuracy_score(y_test, log_reg_preds),
        accuracy_score(y_test, tree_preds),
        accuracy_score(y_test, rf_preds),
        accuracy_score(y_test, gb_preds)
    ],
    "Precision": [
        precision_score(y_test, baseline_preds, zero_division=0),
        precision_score(y_test, log_reg_preds),
        precision_score(y_test, tree_preds),
        precision_score(y_test, rf_preds),
        precision_score(y_test, gb_preds)
    ],
    "Recall": [
        recall_score(y_test, baseline_preds, zero_division=0),
        recall_score(y_test, log_reg_preds),
        recall_score(y_test, tree_preds),
        recall_score(y_test, rf_preds),
        recall_score(y_test, gb_preds)
    ],
    "F1 Score": [
        f1_score(y_test, baseline_preds, zero_division=0),
        f1_score(y_test, log_reg_preds),
        f1_score(y_test, tree_preds),
        f1_score(y_test, rf_preds),
        f1_score(y_test, gb_preds)
    ]
})

results

plt.figure(figsize=(10, 5))
plt.bar(results["Model"], results["F1 Score"])
plt.xlabel("Model")
plt.ylabel("F1 Score")
plt.title("Model Comparison by F1 Score")
plt.xticks(rotation=30)
plt.show()

results.sort_values(by="F1 Score", ascending=False)

from sklearn.metrics import ConfusionMatrixDisplay

ConfusionMatrixDisplay.from_predictions(
    y_test,
    gb_preds,
    display_labels=["Not Popular", "Popular"]
)

plt.title("Confusion Matrix: Gradient Boosting")
plt.show()

rf_importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": rf.feature_importances_
})

rf_importance = rf_importance.sort_values(by="Importance", ascending=False)

rf_importance.head(15)

top_rf_features = rf_importance.head(15)

plt.figure(figsize=(10, 6))
plt.barh(top_rf_features["Feature"], top_rf_features["Importance"])
plt.xlabel("Importance")
plt.ylabel("Feature")
plt.title("Top 15 Feature Importances: Random Forest")
plt.gca().invert_yaxis()
plt.show()

gb_importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": gb.feature_importances_
})

gb_importance = gb_importance.sort_values(by="Importance", ascending=False)

gb_importance.head(15)

top_gb_features = gb_importance.head(15)

plt.figure(figsize=(10, 6))
plt.barh(top_gb_features["Feature"], top_gb_features["Importance"])
plt.xlabel("Importance")
plt.ylabel("Feature")
plt.title("Top 15 Feature Importances: Gradient Boosting")
plt.gca().invert_yaxis()
plt.show()

log_coefficients = pd.DataFrame({
    "Feature": X.columns,
    "Coefficient": log_reg.coef_[0]
})

log_coefficients["Abs Coefficient"] = log_coefficients["Coefficient"].abs()

log_coefficients = log_coefficients.sort_values(
    by="Abs Coefficient",
    ascending=False
)

log_coefficients.head(15)

positive_features = log_coefficients.sort_values(
    by="Coefficient",
    ascending=False
).head(15)

plt.figure(figsize=(10, 6))
plt.barh(positive_features["Feature"], positive_features["Coefficient"])
plt.xlabel("Coefficient")
plt.ylabel("Feature")
plt.title("Top Positive Features: Logistic Regression")
plt.gca().invert_yaxis()
plt.show()

negative_features = log_coefficients.sort_values(
    by="Coefficient",
    ascending=True
).head(15)

plt.figure(figsize=(10, 6))
plt.barh(negative_features["Feature"], negative_features["Coefficient"])
plt.xlabel("Coefficient")
plt.ylabel("Feature")
plt.title("Top Negative Features: Logistic Regression")
plt.gca().invert_yaxis()
plt.show()

results.to_csv("model_comparison_results.csv", index=False)
rf_importance.to_csv("random_forest_feature_importance.csv", index=False)
gb_importance.to_csv("gradient_boosting_feature_importance.csv", index=False)
log_coefficients.to_csv("logistic_regression_coefficients.csv", index=False)

